name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Try to restore opam cache
        if: runner.os != 'Windows'
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: 4.07.1  # OCaml version is key to cache

#       - name: Use OCaml
#         uses: avsm/setup-ocaml@v1
#         with:
#           ocaml-version: 4.07.1
          
#       - run: opam install -y ocamlfind ocamlbuild
#       - run: opam repo add coq-released https://coq.inria.fr/opam/released
#       - run: opam repo add iris-dev https://gitlab.mpi-sws.org/iris/opam.git
#       - run: opam install -y coq-iris.dev.2020-08-07.2.b2b558ac
#       - run: eval $(opam config env)

      - name: Test working directory 3
        working-directory: templates
        run: ls -l

      - name: Test working directory 1
        working-directory: $GITHUB_WORKSPACE/templates
        run: ls -l

      - name: Test working directory 2
        working-directory: ${{ github.workspace }}/templates
        run: ls -l
